#!/usr/bin/zsh

### path
#
export PATH=$HOME/bin:$PATH; wait
export PATH=$HOME/.local/bin:$PATH; wait
export PATH=$HOME/.cargo/bin:$PATH; wait
export PATH=/usr/share:$PATH; wait
export PATH=/usr/local/share:$PATH; wait
export PATH=$HOME/.local/share:$PATH; wait

### user configuration
#
if [ -n "$MANPATH" ]; then
	MANPATH="/usr/local/man"; export MANPATH
else
	export MANPATH="/usr/local/man:$MANPATH"
fi

# compilation flags
export ARCHFLAGS="-arch x86_64"

# language environment
export LANG=en_US.UTF-8

### if
#
if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR='nvim'
else
	export EDITOR='nvim'
fi

if [[ -n $DOTFILES_DIR ]]; then
	export DOTFILES_DIR="$HOME/dotfiles"
else
	export DOTFILES_DIR="$HOME/dotfiles"
fi

if [ -d $HOME/.venv ]; then
	if [ -z $VENV_DIR ]; then
		export VENV_DIR="$HOME/.venv"
	else
		export venvdir="$VENV_DIR"
	fi
fi

if [[ -n $VENV_DIR ]]; then
	if [ -z $venvdir ]; then
		export venvdir="$VENV_DIR"
	fi
fi

if [[ -z $PSHOME ]]; then 
	if [ -e /opt/microsoft/powershell/7 ]; then
		export PSHOME=/opt/microsoft/powershell/7
	else
		export PSHOME=/opt/microsoft/powershell/7
	fi
fi

if [[ -n $PSHOME ]]; then
	if [ -e $HOME/.ps_path ]; then
		. $HOME/dotfiles/login/pspath.sh
	else
		ln -s $HOME/dotfiles/login/pshellrc $HOME/.ps_path && . $HOME/.ps_path
	fi
fi

if [[ -n $DOTFILES_DIR ]]; then
	if [ -z $dotdir ]; then
		export dotdir=$(echo $DOTFILES_DIR)
	else
		export dotdir=$(echo $DOTFILES_DIR)
	fi
fi

