#!/usr/bin/zsh

### path
#
export PATH=$HOME/bin:$PATH; wait
export PATH=$HOME/.local/bin:$PATH; wait
export PATH=$HOME/.cargo/bin:$PATH; wait
export PATH=/usr/share:$PATH; wait
export PATH=/usr/local/share:$PATH; wait
export PATH=$HOME/.local/share:$PATH; wait

### shell
#
# zsh
export ZSH="$HOME/.oh-my-zsh"

### user configuration
#
if [ -n "$MANPATH" ]; then
	MANPATH="/usr/local/man"; export MANPATH
else
	export MANPATH="/usr/local/man:$MANPATH"
fi

# compilation flags
export ARCHFLAGS="-arch x86_64"

# language environment
export LANG=en_US.UTF-8

### if
#
# editor
if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR='nvim'
else
	export EDITOR='nvim'
fi

# export PATH=$HOME/.guix-profile/bin:$PATH; wait
# export PATH=$HOME/repo/sdk/google-cloud-sdk/bin:$PATH; wait
