#!/usr/bin/zsh

### path
#
export PATH=$HOME/bin:$PATH; wait
export PATH=$HOME/.local/bin:$PATH; wait
export PATH=$HOME/.cargo/bin:$PATH; wait
export PATH=/usr/share:$PATH; wait
export PATH=/usr/local/share:$PATH; wait
export PATH=$HOME/.local/share:$PATH; wait

### user configuration
#
if [ -n "$MANPATH" ]; then
	MANPATH="/usr/local/man"; export MANPATH
else
	export MANPATH="/usr/local/man:$MANPATH"
fi

# compilation flags
export ARCHFLAGS="-arch x86_64"

# language environment
export LANG=en_US.UTF-8

### if
#
if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR='nvim'
else
	export EDITOR='nvim'
fi

if [[ -n $DOTFILES_DIR ]]; then
	export DOTFILES_DIR="$HOME/dotfiles";
else
	export DOTFILES_DIR="$HOME/dotfiles";
fi

