#!/usr/bin/zsh

if [ -n "$PATH" ]; then
	PATH='/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games';export PATH
else
	PATH='/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games';export PATH
fi


