#!/usr/bin/zsh


if [ -d "$HOME/.cargo/env" ]; then
	. "$HOME/.cargo/env"
fi

if [ -f "$HOME/.bash_aliases" ]; then
	. $HOME/.bash_aliases
fii

if [ -f "$HOME/.profile" ]; then
	. $HOME/.profile

if [ -f "/usr/share/applications/nitrogen.desktop" ]; then
	nitrogen --resume
fi


