g_fnCallback=function(a){for(var b=0,d=a.requestHeaders.length;b<d;++b)if("User-Agent"==a.requestHeaders[b].name){void 0==m_arrUaList[m_arrConfig.useragent_id]&&(m_arrConfig.useragent_id="default");"default"!=m_arrConfig.useragent_id&&(a.requestHeaders[b].value=m_arrUaList[m_arrConfig.useragent_id].UA);break}return{requestHeaders:a.requestHeaders}};chrome.webRequest.onBeforeSendHeaders.addListener(g_fnCallback,{urls:["<all_urls>"]},["blocking","requestHeaders"]);
chrome.runtime.onMessage.addListener(function(a,b,d){"getUserAgent"==a.action&&(FixConfig(),d({userAgent:"default"==m_arrConfig.useragent_id||0==m_arrConfig.useragent_js?"":m_arrUaList[m_arrConfig.useragent_id].UA,platform:"default"==m_arrConfig.useragent_id||0==m_arrConfig.useragent_js?"":m_arrUaList[m_arrConfig.useragent_id].OS}));return!0});Init();function Init(){LoadLangToStorage();CheckVersion();Reload()}
function CreateMenu(){chrome.contextMenus.removeAll();chrome.contextMenus.create({id:"default",contexts:["all"],title:MYLANG("Default"),type:"checkbox",checked:"default"==m_arrConfig.useragent_id,onclick:function(){ChangeUserAgent("default")}});chrome.contextMenus.create({contexts:["all"],type:"separator"});var a="device"==m_arrConfig.view_type?m_arrDevList:m_arrBwsList,b="device"==m_arrConfig.view_type?"DID":"BID",d="default"==m_arrConfig.useragent_id?"default":m_arrUaList[m_arrConfig.useragent_id][b],
c;for(c in a)for(var e in m_arrUaList)if(m_arrUaList[e][b]==c){chrome.contextMenus.create({id:c,contexts:["all"],title:c==d?"[ "+a[c]+" ]":a[c],type:"normal"});break}chrome.contextMenus.create({contexts:["all"],type:"separator"});chrome.contextMenus.create({id:"VIEW-BY",contexts:["all"],title:MYLANG("UAGroup"),type:"normal"});chrome.contextMenus.create({id:"VIEW-BY-DEV",parentId:"VIEW-BY",contexts:["all"],title:MYLANG("Device"),type:"checkbox",checked:"device"==m_arrConfig.view_type,onclick:function(){ChangeViewType("device")}});
chrome.contextMenus.create({id:"VIEW-BY-BWS",parentId:"VIEW-BY",contexts:["all"],title:MYLANG("Browser"),type:"checkbox",checked:"device"!=m_arrConfig.view_type,onclick:function(){ChangeViewType("browser")}});chrome.contextMenus.create({id:"OPTIONS",contexts:["all"],title:MYLANG("Options"),type:"normal",onclick:function(){return chrome.tabs.create({url:"options.html"})}});chrome.contextMenus.create({id:"CHECKUA",contexts:["all"],title:MYLANG("UACheck"),type:"normal",onclick:function(){return chrome.tabs.create({url:"https://useragent.openadmintools.com/?ref=ext_ua"})}});
for(e in m_arrUaList)(function(a){chrome.contextMenus.create({id:a,parentId:m_arrUaList[a][b],contexts:["all"],title:m_arrUaList[a].NM,type:"checkbox",checked:a==m_arrConfig.useragent_id,onclick:function(){ChangeUserAgent(a)}})})(e)}function Reload(){LoadConfig();CreateMenu();SetBadgeIconText()}function ChangeUserAgent(a){m_arrConfig.useragent_id=a;localStorage.config=JSON.stringify(m_arrConfig);CreateMenu();chrome.tabs.reload();SetBadgeIconText()}
function ChangeViewType(a){m_arrConfig.view_type=a;localStorage.config=JSON.stringify(m_arrConfig);CreateMenu()}function ChangeUaJsmode(a){m_arrConfig.useragent_js=a;localStorage.config=JSON.stringify(m_arrConfig)}
function SetBadgeIconText(){"default"==m_arrConfig.useragent_id?(chrome.browserAction.setIcon({path:"image/logo-19.png"}),chrome.browserAction.setTitle({title:"Http User-Agent Switcher\nCurrent Agent: Default"}),chrome.browserAction.setBadgeText({text:""})):(chrome.browserAction.setIcon({path:"image/logo-19-light.png"}),chrome.browserAction.setTitle({title:"Http User-Agent Switcher\nCurrent User-Agent: "+m_arrUaList[m_arrConfig.useragent_id].NM}),chrome.browserAction.setBadgeText({text:void 0==m_arrUaList[m_arrConfig.useragent_id].FG?
"":m_arrUaList[m_arrConfig.useragent_id].FG}))};
