var m_strLastUAID="";document.addEventListener("DOMContentLoaded",function(){LoadLangToStorage();LoadElements();LoadPageAgents();LoadPageGroups();LoadPageGeneral();LoadPageAbout()});
function LoadElements(){document.title=MYLANG("Options")+" - Http User-Agent Switcher";var a=MYLANG("Rate5Stars").replace(/%LINK%/i,"https://chrome.google.com/webstore/detail/"+chrome.runtime.id+"/reviews");$("#do_you_like").html('<img src="image/rate.png" class="icon_16" ALT=""> '+a);$("#lbl_option").html(MYLANG("Options"));document.getElementById("lnk_agents").innerHTML=document.getElementById("lbl_agents").innerHTML=MYLANG("UAMangeUA");document.getElementById("lnk_group").innerHTML=document.getElementById("lbl_group").innerHTML=
MYLANG("UAMangeGroup");document.getElementById("lnk_general").innerHTML=document.getElementById("lbl_general").innerHTML=MYLANG("MenuGeneral");document.getElementById("lnk_about").innerHTML=document.getElementById("lbl_about").innerHTML=MYLANG("About");$("#lnk_agents").click(function(){OnMenu("lnk_agents")});$("#lnk_group").click(function(){OnMenu("lnk_group")});$("#lnk_general").click(function(){OnMenu("lnk_general")});$("#lnk_about").click(function(){OnMenu("lnk_about")})}
function OnMenu(a){document.getElementById("lnk_agents").className="lnk_agents"==a?"menu_sel":"menu_unsel";document.getElementById("lnk_group").className="lnk_group"==a?"menu_sel":"menu_unsel";document.getElementById("lnk_general").className="lnk_general"==a?"menu_sel":"menu_unsel";document.getElementById("lnk_about").className="lnk_about"==a?"menu_sel":"menu_unsel";document.getElementById("page_agents").className="lnk_agents"==a?"display":"hide";document.getElementById("page_group").className="lnk_group"==
a?"display":"hide";document.getElementById("page_general").className="lnk_general"==a?"display":"hide";document.getElementById("page_about").className="lnk_about"==a?"display":"hide"}
function LoadPageAgents(){LoadAgentsToList(m_arrConfig.useragent_id);$("#wrap_ualist").change(function(){OnChangeUA()});var a='<div class="manage_btns"><button id="btn_add">'+MYLANG("BtnAdd")+'</button><button id="btn_del">'+MYLANG("BtnDelete")+'</button></div><div class="viewtype"><input type="radio" id="f_view_device" name="f_viewtype" value="device"'+("device"==m_arrConfig.view_type?" checked":"")+'> <label for="f_view_device">'+MYLANG("UAGroupDev")+'</label></div><div class="viewtype"><input type="radio" id="f_view_browser" name="f_viewtype" value="browser"'+
("browser"==m_arrConfig.view_type?" checked":"")+'> <label for="f_view_browser">'+MYLANG("UAGroupBrowser")+"</label></div>";$("#wrap_buttons").html(a);OnChangeUA();$("#f_view_device").click(function(){OnSetViewType("device")});$("#f_view_browser").click(function(){OnSetViewType("browser")});$("#btn_add").click(function(){OnAddUA()});$("#btn_del").click(function(){OnDelUA()})}function LoadPageGroups(){LoadGroupToList("bws");LoadGroupToList("dev")}
function LoadPageGeneral(){var a='<table><tr><td class="td_chk"><input type="checkbox" value="" name="ipt_jsua" id="ipt_jsua" '+(m_arrConfig.useragent_js?"":"checked")+'></td><td class="td_desc"><label for="ipt_jsua">'+MYLANG("UAChangeJsUa")+"</label>  "+MYLANG("UAChangeJsUaDesc")+'</td></tr>  <tr><td colspan=2 class="td_title">'+MYLANG("BtnResetSettings")+'</td></tr>  <tr><td></td><td class="td_desc">'+MYLANG("BtnResetDesc")+'<br><button id="btn_reset">'+MYLANG("BtnResetSettings")+"</button></td></tr>  </table>";
$("#wrap_general").html(a);$("#ipt_jsua").click(function(){OnJsUA()});$("#btn_reset").click(function(){OnReset()})}
function LoadPageAbout(){var a=chrome.app.getDetails().version,a=MYLANG("VerInfo").replace("%VER%",a),a=a.replace("%AUTHOR%",'<a href="https://www.openadmintools.com/?ref=ext_ua" target=_blank title="OpenAdminTools.com">OpenAdminToos</a>'),a='<div class="about_name"><div class="about_title">Http User-Agent Switcher</div><div class="about_ver">'+a+'</div></div>    <div class="about_desc">'+MYLANG("UAExtDesc")+" "+MYLANG("UAExtDesc2")+'</DIV>    <div class="about_desc"><ul><li>'+MYLANG("UAExtDesc3")+
"</li><li>"+MYLANG("UAExtDesc4")+"</li><li>"+MYLANG("UAExtDesc5")+'</li></ul></DIV>    <div class="about_desc">'+MYLANG("UAExtDesc6")+'</DIV>    <div class="about_links">      <img src="image/icon-home.png" class="icon_16"> '+MYLANG("Support")+': <a href="https://app.openadmintools.com/'+MYLANG("id")+'/http-user-agent-switcher/" target=_blank">Http User-Agent Switcher</a><br>      <img src="image/icon-email16.png" class="icon_16"> '+MYLANG("Feedback")+': <a href="mailto:support@OpenAdminTools.com">support@OpenAdminTools.com</a>    </div>';
$("#wrap_about").html(a)}
function LoadGroupToList(a){var b="dev"==a?m_arrDevList:m_arrBwsList,c='<DIV class="grouptitle">'+MYLANG("dev"==a?"Device":"Browser")+':</div><SELECT SIZE=5 id="'+a+'_list">',d;for(d in b)c+='<option value="'+d+'">'+b[d]+"</option>";$("#wrap_"+a+"list").html(c+"</select>");$("#wrap_"+a+"list").click(function(){OnGroupChange(a)});b='<div class="manage_btns"><button id="btn_'+a+'add">'+MYLANG("BtnAdd")+'</button><button id="btn_'+a+'edit">'+MYLANG("BtnEdit")+'</button><button id="btn_'+a+'del">'+MYLANG("BtnDelete")+
"</button></div>";$("#wrap_"+a+"btn").html(b);$("#btn_"+a+"add").click(function(){OnGroupAdd(a)});$("#btn_"+a+"edit").click(function(){OnGroupEdit(a)});$("#btn_"+a+"del").click(function(){OnGroupDel(a)});OnGroupChange(a)}function OnGroupChange(a){var b=GetSelectedVal(a+"_list"),b=""==b||"Other"==b;document.getElementById("btn_"+a+"edit").disabled=b;document.getElementById("btn_"+a+"del").disabled=b}
function OnGroupAdd(a){var b="bws"==a?MYLANG("BrowserName"):MYLANG("DeviceName");$("#pop_window").html('<div class="pop_title"><span>'+MYLANG("BtnAdd")+'</span></div><div class="pop_desc">  <div class="edit_title">'+b+':</DIV><div class="edit_ctrl"><input name="ipt_group" id="ipt_group" placeholder="'+MYLANG("PleaseEnter").replace("%NAME%",b)+'" value=""></div></div><div class="pop_btns"><button id="btn_yes">'+MYLANG("BtnAdd")+'</button><button id="btn_no">'+MYLANG("BtnCancel")+"</button></div>");
document.getElementById("pop_window").className="pop_group";$("#pop_window").lightbox_me({centered:!0,onLoad:function(){$("#btn_yes").click(function(){AddGroup(a)});$("#btn_no").click(function(){$("#pop_window").trigger("close");$("#pop_window").html("")})}})}
function AddGroup(a){var b=document.getElementById("ipt_group");if(""==b.value)b.className="edit_error";else{$("#pop_window").trigger("close");var c=a+Math.round(+new Date/1E3);"bws"==a?(m_arrBwsList[c]=b.value,localStorage.list_browser=JSON.stringify(m_arrBwsList)):(m_arrDevList[c]=b.value,localStorage.list_device=JSON.stringify(m_arrDevList));LoadGroupToList(a);OnChangeUA();$("#pop_window").html("")}}
function OnAddUA(){var a='<SELECT id="ipt_add_browser"><optgroup label="--- '+MYLANG("PleaseSelect")+' ---">',b='<SELECT id="ipt_add_device"><optgroup label="--- '+MYLANG("PleaseSelect")+' ---">',c;for(c in m_arrBwsList)a+='<option value="'+c+'">'+m_arrBwsList[c]+"</option>";for(c in m_arrDevList)b+='<option value="'+c+'">'+m_arrDevList[c]+"</option>";a+="</optgroup></SELECT>";b+="</optgroup></SELECT>";$("#pop_window").html('<div class="pop_title"><span>'+MYLANG("BtnAdd")+'</span></div><div class="pop_desc">  <div class="edit_title">'+
MYLANG("UANameUA")+':</DIV><div class="edit_ctrl"><input name="ipt_add_name" id="ipt_add_name" placeholder="'+MYLANG("PleaseEnter").replace("%NAME%",MYLANG("UANameUA"))+'" value=""></div>  <div class="edit_title">'+MYLANG("UAFlag")+"("+MYLANG("UAFlagLen")+'):</div><div class="edit_ctrl"><input name="ipt_add_flag" id="ipt_add_flag" placeholder="'+MYLANG("UAFlagLen")+'" value=""></div>  <div class="edit_title">'+MYLANG("UAString")+':</div><div class="edit_ctrl"><textarea rows=3 cols=20 name="ipt_add_ua" id="ipt_add_ua" placeholder="'+
MYLANG("PleaseEnter").replace("%NAME%",MYLANG("UAString"))+'"></TEXTAREA></div>  <div class="edit_title">'+MYLANG("Platform")+':</div><div class="edit_ctrl"><input name="ipt_add_os" id="ipt_add_os" placeholder="'+MYLANG("Platform")+'" value=""></div>  <div class="edit_title">'+MYLANG("Browser")+':</div><div class="edit_ctrl">'+a+'</div>  <div class="edit_title">'+MYLANG("Device")+':</div><div class="edit_ctrl">'+b+'</div></div><div class="pop_btns"><button id="btn_yes">'+MYLANG("BtnAdd")+'</button><button id="btn_no">'+
MYLANG("BtnCancel")+"</button></div>");document.getElementById("pop_window").className="pop_add";$("#pop_window").lightbox_me({centered:!0,onLoad:function(){$("#ipt_add_flag").change(function(){var a=document.getElementById("ipt_add_flag"),b=a.value;4<b.length&&(a.value=b.substring(0,4))});$("#btn_yes").click(function(){AddUA()});$("#btn_no").click(function(){$("#pop_window").trigger("close");$("#pop_window").html("")})}})}
function OnDelUA(){var a=GetSelectedText("ua_list");$("#pop_window").html('<div class="pop_desc pop_desc_del">'+MYLANG("BtnDeleteConfirm").replace("%NAME%","<b>"+a+"</b>")+'</div><div class="pop_btns"><button id="btn_yes">'+MYLANG("BtnDelete")+'</button><button id="btn_no">'+MYLANG("BtnCancel")+"</button></div>");document.getElementById("pop_window").className="pop_delete";$("#pop_window").lightbox_me({centered:!0,onLoad:function(){$("#btn_yes").click(function(){DeleteUA()});$("#btn_no").click(function(){$("#pop_window").trigger("close");
$("#pop_window").html("")})}})}function DeleteUA(){$("#pop_window").trigger("close");$("#pop_window").html("");var a=GetSelectedVal("ua_list");"default"!=a&&(delete m_arrUaList[a],localStorage.list_ua=JSON.stringify(m_arrUaList),a==m_arrConfig.useragent_id&&(m_arrConfig.useragent_id="default"),LoadAgentsToList(m_arrConfig.useragent_id),OnChangeUA(),chrome.extension.getBackgroundPage().Reload())}
function OnSetViewType(a){a!=m_arrConfig.view_type&&(m_arrConfig.view_type=a,localStorage.config=JSON.stringify(m_arrConfig),LoadAgentsToList(GetSelectedVal("ua_list")),chrome.extension.getBackgroundPage().ChangeViewType(a))}
function OnChangeUA(){var a=GetSelectedVal("ua_list");m_strLastUAID=a;if("default"==a)$("#wrap_edit").html('<div class="edit_title">'+MYLANG("UACantEdit")+"</div>"),document.getElementById("btn_del").disabled=!0;else{document.getElementById("btn_del").disabled=!1;var b='<SELECT id="ipt_browser"><optgroup label="--- '+MYLANG("PleaseSelect")+' ---">',c='<SELECT id="ipt_device"><optgroup label="--- '+MYLANG("PleaseSelect")+' ---">',d;for(d in m_arrBwsList)b+='<option value="'+d+'"'+(d==m_arrUaList[a].BID?
" selected":"")+">"+m_arrBwsList[d]+"</option>";for(d in m_arrDevList)c+='<option value="'+d+'"'+(d==m_arrUaList[a].DID?" selected":"")+">"+m_arrDevList[d]+"</option>";a='<div class="edit_title">'+MYLANG("UANameUA")+':</DIV><div class="edit_ctrl"><input name="ipt_name" id="ipt_name" placeholder="'+MYLANG("PleaseEnter").replace("%NAME%",MYLANG("UANameUA"))+'" value="'+m_arrUaList[a].NM+'"></div><div class="edit_title">'+MYLANG("UAFlag")+"("+MYLANG("UAFlagLen")+'):</div><div class="edit_ctrl"><input name="ipt_flag" id="ipt_flag" placeholder="'+
MYLANG("UAFlagLen")+'" value="'+m_arrUaList[a].FG+'"></div><div class="edit_title">'+MYLANG("UAString")+':</div><div class="edit_ctrl"><textarea rows=3 cols=20 name="ipt_ua" id="ipt_ua" placeholder="'+MYLANG("PleaseEnter").replace("%NAME%",MYLANG("UAString"))+'">'+m_arrUaList[a].UA+'</TEXTAREA></div><div class="edit_title">'+MYLANG("Platform")+':</div><div class="edit_ctrl"><input name="ipt_os" id="ipt_os" placeholder="'+MYLANG("PleaseEnter").replace("%NAME%",MYLANG("Platform"))+'" value="'+m_arrUaList[a].OS+
'"></div><div class="edit_title">'+MYLANG("Browser")+':</div><div class="edit_ctrl">'+(b+"</optgroup></SELECT>")+'</div><div class="edit_title">'+MYLANG("Device")+':</div><div class="edit_ctrl">'+(c+"</optgroup></SELECT>")+"</div>";$("#wrap_edit").html(a);$("#ipt_name").change(function(){OnEditUA("ipt_name")});$("#ipt_flag").change(function(){OnEditUA("ipt_flag")});$("#ipt_ua").change(function(){OnEditUA("ipt_ua")});$("#ipt_os").change(function(){OnEditUA("ipt_os")});$("#ipt_browser").change(function(){OnEditUA("ipt_browser")});
$("#ipt_device").change(function(){OnEditUA("ipt_device")})}}
function AddUA(){var a=document.getElementById("ipt_add_name"),b=document.getElementById("ipt_add_flag"),c=document.getElementById("ipt_add_ua"),d=document.getElementById("ipt_add_os"),e=0;""==a.value?(a.className="edit_error",e=1):a.className="";""==b.value?(b.className="edit_error",e=1):b.className="";""==c.value?(c.className="edit_error",e=1):c.className="";e||($("#pop_window").trigger("close"),e="UA"+Math.round(+new Date/1E3),m_arrUaList[e]={DID:GetSelectedVal("ipt_add_device"),BID:GetSelectedVal("ipt_add_browser"),
FG:b.value,NM:a.value,UA:c.value,OS:d.value},localStorage.list_ua=JSON.stringify(m_arrUaList),LoadAgentsToList(e),OnChangeUA(),chrome.extension.getBackgroundPage().Reload(),$("#pop_window").html(""))}
function OnGroupDel(a){var b=GetSelectedText(a+"_list");""!=b&&($("#pop_window").html('<div class="pop_desc pop_desc_del">'+MYLANG("BtnDeleteConfirm").replace("%NAME%","<b>"+b+"</b>")+'</div><div class="pop_btns"><button id="btn_yes">'+MYLANG("BtnDelete")+'</button><button id="btn_no">'+MYLANG("BtnCancel")+"</button></div>"),document.getElementById("pop_window").className="pop_delete",$("#pop_window").lightbox_me({centered:!0,onLoad:function(){$("#btn_yes").click(function(){DeleteGroup(a)});$("#btn_no").click(function(){$("#pop_window").trigger("close");
$("#pop_window").html("")})}}))}
function DeleteGroup(a){$("#pop_window").trigger("close");$("#pop_window").html("");var b=document.getElementById(a+"_list"),b=b.options[b.selectedIndex].value,c="";"bws"==a?(delete m_arrBwsList[b],localStorage.list_browser=JSON.stringify(m_arrBwsList),c="BID"):(delete m_arrDevList[b],localStorage.list_device=JSON.stringify(m_arrDevList),c="DID");var d=0,e;for(e in m_arrUaList)m_arrUaList[e][c]==b&&(m_arrUaList[e][c]="Other",d=1);d&&(localStorage.list_ua=JSON.stringify(m_arrUaList));LoadGroupToList(a);
LoadAgentsToList(GetSelectedVal("ua_list"));OnChangeUA();chrome.extension.getBackgroundPage().Reload()}
function OnGroupEdit(a){var b=GetSelectedText(a+"_list");if(""!=b){var c="bws"==a?MYLANG("BrowserName"):MYLANG("DeviceName");$("#pop_window").html('<div class="pop_title"><span>'+MYLANG("BtnEdit")+'</span></div><div class="pop_desc">  <div class="edit_title">'+c+':</DIV><div class="edit_ctrl"><input name="ipt_group" id="ipt_group" placeholder="'+MYLANG("PleaseEnter").replace("%NAME%",c)+'" value="'+b+'"></div></div><div class="pop_btns"><button id="btn_yes">'+MYLANG("BtnSave")+'</button><button id="btn_no">'+
MYLANG("BtnCancel")+"</button></div>");document.getElementById("pop_window").className="pop_group";$("#pop_window").lightbox_me({centered:!0,onLoad:function(){$("#btn_yes").click(function(){EditGroup(a)});$("#btn_no").click(function(){$("#pop_window").trigger("close");$("#pop_window").html("")})}})}}
function EditGroup(a){var b=document.getElementById("ipt_group"),c=b.value;if(""==c)b.className="edit_error";else{$("#pop_window").trigger("close");var b=document.getElementById(a+"_list"),d=b.options[b.selectedIndex].value;b.options[b.selectedIndex].text=c;"bws"==a?(m_arrBwsList[d]=c,localStorage.list_browser=JSON.stringify(m_arrBwsList)):(m_arrDevList[d]=c,localStorage.list_device=JSON.stringify(m_arrDevList));$("#pop_window").html("");LoadAgentsToList(GetSelectedVal("ua_list"));OnChangeUA();chrome.extension.getBackgroundPage().Reload()}}
function OnEditUA(a){var b=document.getElementById("ua_list");if(-1!=b.selectedIndex){var c=b.options[b.selectedIndex].value,d=document.getElementById(a);if("ipt_name"==a||"ipt_flag"==a||"ipt_ua"==a||"ipt_os"==a){var e=d.value;if(""==e&&"ipt_os"!=a){d.className="edit_error";return}d.className="";"ipt_name"==a&&(m_arrUaList[c].NM=e,b.options[b.selectedIndex].text=e);"ipt_flag"==a&&(4<e.length&&(e=e.substring(0,4),d.value=e),m_arrUaList[c].FG=e);"ipt_ua"==a&&(m_arrUaList[c].UA=e);"ipt_os"==a&&(m_arrUaList[c].OS=
e)}"ipt_browser"==a&&(e=d.options[d.selectedIndex].value,m_arrUaList[c].BID=e,"browser"==m_arrConfig.view_type&&LoadAgentsToList(c));"ipt_device"==a&&(e=d.options[d.selectedIndex].value,m_arrUaList[c].DID=e,"device"==m_arrConfig.view_type&&LoadAgentsToList(c));localStorage.list_ua=JSON.stringify(m_arrUaList);chrome.extension.getBackgroundPage().Reload()}}
function OnReset(){$("#pop_window").html('<div class="pop_desc pop_desc_reset">'+MYLANG("BtnResetDesc")+'</div><div class="pop_btns"><button id="btn_yes">'+MYLANG("BtnReset")+'</button><button id="btn_no">'+MYLANG("BtnCancel")+"</button></div>");document.getElementById("pop_window").className="pop_delete";$("#pop_window").lightbox_me({centered:!0,onLoad:function(){$("#btn_yes").click(function(){LoadDefault();chrome.extension.getBackgroundPage().Reload();window.location.reload()});$("#btn_no").click(function(){$("#pop_window").trigger("close");
$("#pop_window").html("")})}})}function OnJsUA(){m_arrConfig.useragent_js=document.getElementById("ipt_jsua").checked?0:1;chrome.extension.getBackgroundPage().ChangeUaJsmode(m_arrConfig.useragent_js)};
